name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    name: Test RabbitMQ Docker image version [${{ matrix.version }}]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['3.8.9', 'latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start RabbitMQ
        uses: ./
        with:
          version: ${{ matrix.version }}

  test-definition:
    name: Test RabbitMQ Docker image version [${{ matrix.version }}] with definition 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['3.8.9-management', 'management']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start RabbitMQ
        uses: ./
        with:
          version: ${{ matrix.version }}
          definition: ${{ github.workspace }}/definition.json
